[package]
name = "movies-db"
version = "0.1.0"
authors = ["Grégory Obanos <gregory.obanos@gmail.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4", features = ["sqlite"] }
dotenv = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"